"""restore workspace constraints dropped by autogenerate artifact

Migration 09e259f2471d was generated by `alembic revision --autogenerate` while
analysing_jobs was being added. Autogenerate saw naming-convention mismatches on
pre-existing indexes and dropped them — but only recreated the ones whose column
names had changed. The result: three tables lost indexes, workspace_members lost
its duplicate-membership unique constraint, and workspaces lost its owner_id FK.

Revision ID: 0007
Revises: a1f3c8e2d094
Create Date: 2026-04-27
"""
from alembic import op

revision = "0007"
down_revision = "a1f3c8e2d094"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # workspace_members — restore query indexes and duplicate-membership guard
    op.create_index("ix_workspace_members_workspace_id", "workspace_members", ["workspace_id"])
    op.create_index("ix_workspace_members_user_id", "workspace_members", ["user_id"])
    op.create_unique_constraint(
        "uq_workspace_members_workspace_user",
        "workspace_members",
        ["workspace_id", "user_id"],
    )

    # workspaces — restore owner_id index and FK to users
    op.create_index("ix_workspaces_owner_id", "workspaces", ["owner_id"])
    op.create_foreign_key(
        "workspaces_owner_id_fkey", "workspaces", "users", ["owner_id"], ["id"]
    )

    # workspace_invites — workspace_id index was dropped and not recreated
    op.create_index("ix_workspace_invites_workspace_id", "workspace_invites", ["workspace_id"])


def downgrade() -> None:
    op.drop_index("ix_workspace_invites_workspace_id", table_name="workspace_invites")
    op.drop_constraint("workspaces_owner_id_fkey", "workspaces", type_="foreignkey")
    op.drop_index("ix_workspaces_owner_id", table_name="workspaces")
    op.drop_constraint("uq_workspace_members_workspace_user", "workspace_members", type_="unique")
    op.drop_index("ix_workspace_members_user_id", table_name="workspace_members")
    op.drop_index("ix_workspace_members_workspace_id", table_name="workspace_members")
