"""add analysis_jobs table

Revision ID: 09e259f2471d
Revises: 0005
Create Date: 2026-04-08 23:59:13.723220

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '09e259f2471d'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.Enum('kaplan_meier', 'regression', 'descriptive_stats', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='jobstatus'), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_dataset_id'), 'analysis_jobs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_workspace_id'), 'analysis_jobs', ['workspace_id'], unique=False)
    op.drop_constraint('users_email_hash_key', 'users', type_='unique')
    op.drop_index('ix_users_email_hash', table_name='users')
    op.create_index(op.f('ix_users_email_hash'), 'users', ['email_hash'], unique=True)
    op.drop_index('ix_workspace_invites_email_hash', table_name='workspace_invites')
    op.drop_index('ix_workspace_invites_workspace_id', table_name='workspace_invites')
    op.create_index(op.f('ix_workspace_invites_invited_email_hash'), 'workspace_invites', ['invited_email_hash'], unique=False)
    op.drop_index('ix_workspace_members_user_id', table_name='workspace_members')
    op.drop_index('ix_workspace_members_workspace_id', table_name='workspace_members')
    op.drop_constraint('uq_workspace_members_workspace_user', 'workspace_members', type_='unique')
    op.drop_index('ix_workspaces_owner_id', table_name='workspaces')
    op.drop_constraint('workspaces_owner_id_fkey', 'workspaces', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('workspaces_owner_id_fkey', 'workspaces', 'users', ['owner_id'], ['id'])
    op.create_index('ix_workspaces_owner_id', 'workspaces', ['owner_id'], unique=False)
    op.create_unique_constraint('uq_workspace_members_workspace_user', 'workspace_members', ['workspace_id', 'user_id'])
    op.create_index('ix_workspace_members_workspace_id', 'workspace_members', ['workspace_id'], unique=False)
    op.create_index('ix_workspace_members_user_id', 'workspace_members', ['user_id'], unique=False)
    op.drop_index(op.f('ix_workspace_invites_invited_email_hash'), table_name='workspace_invites')
    op.create_index('ix_workspace_invites_workspace_id', 'workspace_invites', ['workspace_id'], unique=False)
    op.create_index('ix_workspace_invites_email_hash', 'workspace_invites', ['invited_email_hash'], unique=False)
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.create_index('ix_users_email_hash', 'users', ['email_hash'], unique=False)
    op.create_unique_constraint('users_email_hash_key', 'users', ['email_hash'])
    op.drop_index(op.f('ix_analysis_jobs_workspace_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_dataset_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###