"""add analysis_jobs table

Revision ID: 0db05e37591c
Revises: 09e259f2471d
Create Date: 2026-04-17 23:21:18.791753

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0db05e37591c'
down_revision: Union[str, None] = '09e259f2471d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###